### ISSUE TITLE
Plugin not found while trying out macvlan plugin

### ISSUE THREAD

**Issue by bbhikkaji** [gopher-net/macvlan-docker-plugin#11]
1) Have following.

root@K8Dev:~/macvlan-docker-plugin/binaries# docker -v
Docker version 1.9.1, build a34a1d5

root@K8Dev:~/macvlan-docker-plugin/binaries# lsmod | grep macvlan
macvlan                19046  0

2) Followed the link, and tried this. Throws error

root@K8Dev:~/macvlan-docker-plugin/binaries# docker network create -d macvlan --subnet=10.11.181.0/24 --gateway=10.11.181.254 -o host_iface=eth0 net1

Error response from daemon: Plugin not found

3) Logs below

DEBU[0173] Calling POST /v1.21/networks/create
INFO[0173] POST /v1.21/networks/create
WARN[0173] Unable to locate plugin: macvlan, retrying in 1s
WARN[0174] Unable to locate plugin: macvlan, retrying in 2s
WARN[0176] Unable to locate plugin: macvlan, retrying in 4s
WARN[0180] Unable to locate plugin: macvlan, retrying in 8s
ERRO[0188] Handler for POST /v1.21/networks/create returned error: Plugin not found
ERRO[0188] HTTP Error 

4) Full logs

DEBU[0000] Registering ipam provider: default
DEBU[0000] releasing IPv4 pools from network bridge (f10d1b12beca76f6e09ce395a2ba72d0cc249f86414563cbaf16b885abe164f3)
DEBU[0000] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.1)
DEBU[0000] Retrieving bitmask (LocalDefault/172.17.0.0/16, 172.17.0.0/16)
DEBU[0000] ReleasePool(LocalDefault/172.17.0.0/16)
INFO[0000] Default bridge (docker0) is assigned with an IP address 172.17.0.1/16. Daemon option --bip can be used to set a preferred IP address
DEBU[0000] Allocating IPv4 pools for network bridge (5062d8a42fe3950495226f800c2f2c164dd09b9d857dccda34ce12e21697e3d2)
DEBU[0000] RequestPool(LocalDefault, 172.17.0.1/16, , map[], false)
DEBU[0000] RequestAddress(LocalDefault/172.17.0.0/16, 172.17.0.1, map[])
DEBU[0000] /sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE]
DEBU[0000] /sbin/iptables, [--wait -D FORWARD -i docker0 -o docker0 -j DROP]
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT]
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT]
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT]
DEBU[0000] /sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]
DEBU[0000] /sbin/iptables, [--wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]
DEBU[0000] /sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8]
DEBU[0000] /sbin/iptables, [--wait -t nat -A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8]
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER]
WARN[0000] Your kernel does not support swap memory limit.
WARN[0000] Your kernel does not support kernel memory limit.
DEBU[0000] Cleaning up old shm/mqueue mounts: start.
DEBU[0000] Cleaning up old shm/mqueue mounts: done.
INFO[0000] Daemon has completed initialization
INFO[0000] Docker daemon                                 commit=a34a1d5 execdriver=native-0.2 graphdriver=aufs version=1.9.1
DEBU[0000] Registering routers
DEBU[0000] Registering HEAD, /containers/{name:._}/archive
DEBU[0000] Registering OPTIONS, /
DEBU[0000] Registering GET, /_ping
DEBU[0000] Registering GET, /events
DEBU[0000] Registering GET, /info
DEBU[0000] Registering GET, /version
DEBU[0000] Registering GET, /images/json
DEBU[0000] Registering GET, /images/search
DEBU[0000] Registering GET, /images/get
DEBU[0000] Registering GET, /images/{name:._}/get
DEBU[0000] Registering GET, /images/{name:._}/history
DEBU[0000] Registering GET, /images/{name:._}/json
DEBU[0000] Registering GET, /containers/json
DEBU[0000] Registering GET, /containers/{name:._}/export
DEBU[0000] Registering GET, /containers/{name:._}/changes
DEBU[0000] Registering GET, /containers/{name:._}/json
DEBU[0000] Registering GET, /containers/{name:._}/top
DEBU[0000] Registering GET, /containers/{name:._}/logs
DEBU[0000] Registering GET, /containers/{name:._}/stats
DEBU[0000] Registering GET, /containers/{name:._}/attach/ws
DEBU[0000] Registering GET, /exec/{id:._}/json
DEBU[0000] Registering GET, /containers/{name:._}/archive
DEBU[0000] Registering GET, /volumes
DEBU[0000] Registering GET, /volumes/{name:._}
DEBU[0000] Registering POST, /auth
DEBU[0000] Registering POST, /commit
DEBU[0000] Registering POST, /build
DEBU[0000] Registering POST, /images/create
DEBU[0000] Registering POST, /images/load
DEBU[0000] Registering POST, /images/{name:._}/push
DEBU[0000] Registering POST, /images/{name:._}/tag
DEBU[0000] Registering POST, /containers/create
DEBU[0000] Registering POST, /containers/{name:._}/kill
DEBU[0000] Registering POST, /containers/{name:._}/pause
DEBU[0000] Registering POST, /containers/{name:._}/unpause
DEBU[0000] Registering POST, /containers/{name:._}/restart
DEBU[0000] Registering POST, /containers/{name:._}/start
DEBU[0000] Registering POST, /containers/{name:._}/stop
DEBU[0000] Registering POST, /containers/{name:._}/wait
DEBU[0000] Registering POST, /containers/{name:._}/resize
DEBU[0000] Registering POST, /containers/{name:._}/attach
DEBU[0000] Registering POST, /containers/{name:._}/copy
DEBU[0000] Registering POST, /containers/{name:._}/exec
DEBU[0000] Registering POST, /exec/{name:._}/start
DEBU[0000] Registering POST, /exec/{name:._}/resize
DEBU[0000] Registering POST, /containers/{name:._}/rename
DEBU[0000] Registering POST, /volumes/create
DEBU[0000] Registering PUT, /containers/{name:._}/archive
DEBU[0000] Registering DELETE, /containers/{name:._}
DEBU[0000] Registering DELETE, /images/{name:._}
DEBU[0000] Registering DELETE, /volumes/{name:._}
DEBU[0000] Registering GET, /networks
DEBU[0000] Registering GET, /networks/{id:._}
DEBU[0000] Registering POST, /networks/create
DEBU[0000] Registering POST, /networks/{id:._}/connect
DEBU[0000] Registering POST, /networks/{id:._}/disconnect
DEBU[0000] Registering DELETE, /networks/{id:._}

**Comment by nerdalert** [comment]
Hi @bharbhi was the driver running at the same time as the network request? When you start the driver it should create a file named `/var/run/docker/plugins/macvlan.sock`. Maybe shoot over driver logs? Thanks!

**Comment by nerdalert** [comment]
Hey @bharbhi I just wanted to add a link to the native macvlan driver we are working on getting upstream. The notes are here: [Macvlan, Ipvlan and 802.1q Trunk Native Docker Support Notes](https://gist.github.com/nerdalert/c0363c15d20986633fda)

It is a native driver so there is no need to run a separate daemon like with this repo's 3rd party remote driver process. There is a link to the binary at the top of the notes in the link above. Thanks!
