### ISSUE TITLE
Network Id is not persistent after plugin restart

### ISSUE THREAD

**Issue by kevinxucs** [gopher-net/macvlan-docker-plugin#9]
After plugin restarted, restarting docker container will give following error:

```
Error response from daemon: Cannot start container 2b9d5d291bce: failed to create endpoint mad_wozniak on network net0: remote: No such network bb675fb7bb57c5e6df57f3173a24a7b14ec337e2b9a188fcc5847bd295d14c79
Error: failed to start containers: [2b9d5d291bce]
```

Workaround is to re-create the docker network again so that the id can be registered with the plugin.

It would be nice to keep the network id persistent.

**Comment by nerdalert** [comment]
Hey @kevinxucs I just patched this where if the plugin stops and restarts it will recover. It doesn't manage the scenario if the Docker daemon isn't running at driver runtime though. So I will need to move the code around to check Docker endpoint network cache when a `join` is called. Will get it resolved later, I just realized the last patch doesn't catch all scenarios. Thanks for the patience!

**Comment by nerdalert** [comment]
This is resolved now. If a network is not found during a container `join`, the local Docker engine is queried for the network list to see if it exists. Thanks for the help opening the issue!
